import React from 'react';

// material-ui
import { Grid, Paper, Tab, Tabs, Typography } from '@mui/material';

// project imports
import UserProfile from './UserProfile';

import ChangePassword from './ChangePassword';
import useConfig from 'hooks/useConfig';

// assets
import PersonOutlineTwoToneIcon from '@mui/icons-material/PersonOutlineTwoTone';
import VpnKeyTwoToneIcon from '@mui/icons-material/VpnKeyTwoTone';
import { TabsProps } from 'types';
import GppGoodIcon from '@mui/icons-material/GppGood';
import OtpAuthenticator from './OtpAuthenticator';
import { ProfileTabs } from './profile.styles';
import PageTitle from 'components/page-title/PageTitle';
import UserProfileIcon from 'components/icons/UserProfile';
import PasswordLockIcon from 'components/icons/Password';

// tabs
function TabPanel({ children, value, index, ...other }: TabsProps) {
    return (
        <div role="tabpanel" hidden={value !== index} id={`simple-tabpanel-${index}`} aria-labelledby={`simple-tab-${index}`} {...other}>
            {value === index && <div>{children}</div>}
        </div>
    );
}

function a11yProps(index: number) {
    return {
        id: `simple-tab-${index}`,
        'aria-controls': `simple-tabpanel-${index}`
    };
}

// tabs option
const tabsOption = [
    {
        label: 'User profile',
        icon: <UserProfileIcon />,
        caption: 'Profile Settings'
    },
    {
        label: 'Password settings',
        icon: <PasswordLockIcon />,
        caption: 'Update Profile Security'
    },
    {
        label: 'Multi-factor Authentication',
        icon: <GppGoodIcon />,
        caption: 'Use time-based OTPs generated by authenticator apps to securely sign in to your account.'
    }
];

// ==============================|| PROFILE 2 ||============================== //

const Profile2 = () => {
    const [value, setValue] = React.useState<number>(0);

    const handleChange = (event: React.SyntheticEvent, newValue: number) => {
        setValue(newValue);
    };

    return (
        <>
            <PageTitle title="Account settings" />
            <Grid container className="tabset-grid" spacing={2.2}>
                <Grid item xs={12} lg={2.41}>
                    <Paper className="tabset-list">
                        <Tabs
                            className="profile-tab"
                            value={value}
                            indicatorColor="primary"
                            onChange={handleChange}
                            aria-label="user profile tabs"
                            variant="scrollable"
                            orientation="vertical"
                        >
                            {tabsOption.map((tab, index) => (
                                <Tab
                                    key={index}
                                    icon={React.cloneElement(tab.icon, {
                                        color: value === index ? '#FFFFFF' : '#212121'
                                    })}
                                    label={
                                        <Grid container direction="column">
                                            <Typography variant="subtitle1" color="inherit">
                                                {tab.label}
                                            </Typography>
                                        </Grid>
                                    }
                                    {...a11yProps(index)}
                                />
                            ))}
                        </Tabs>
                    </Paper>
                </Grid>
                <Grid item xs={12} lg={9.59}>
                    <Paper className="tabset-content">
                        <TabPanel value={value} index={0}>
                            <UserProfile />
                        </TabPanel>
                        <TabPanel value={value} index={1}>
                            <ChangePassword />
                        </TabPanel>
                        <TabPanel value={value} index={2}>
                            <OtpAuthenticator />
                        </TabPanel>
                    </Paper>
                </Grid>
            </Grid>
        </>
    );
};

export default Profile2;
